(()=>{const catalogData=[
      {name:"Компьютеры",icon:"💻",items:[["Ноутбуки","rgw_page_laptops.html"],["Моноблоки","rgw_page_monoblocks.html"],["Системные блоки","rgw_page_system_units.html"]]},
      {name:"Комплектующие",icon:"🧩",items:[["Видеокарты","rgw_page_gpus.html"],["Процессоры","rgw_page_processors.html"],["Материнские платы","rgw_page_motherboards.html"],["Оперативная память","rgw_page_ram.html"],["SSD","rgw_page_ssd.html"],["HDD","rgw_page_hdd.html"],["Корпуса","rgw_page_cases.html"],["Блоки питания","rgw_page_power_supplies.html"],["Охлаждение","rgw_page_cooling.html"]]},
      {name:"Периферия",icon:"⌨️",items:[["Мониторы","rgw_page_monitors.html"],["Клавиатуры","rgw_page_keyboards.html"],["Мыши","rgw_page_mice.html"],["Наушники","rgw_page_headphones.html"],["Колонки","rgw_page_speakers.html"],["Веб-камеры","rgw_page_webcams.html"]]},
      {name:"Печать",icon:"🖨️",items:[["Принтеры и МФУ","rgw_page_printers.html"],["Картриджи","rgw_page_cartridges.html"],["Расходные материалы","rgw_page_print_consumables.html"]]},
      {name:"Сетевое оборудование",icon:"📡",items:[["Роутеры","rgw_page_routers.html"],["Mesh-системы","rgw_page_mesh.html"],["Коммутаторы","rgw_page_switches.html"],["Wi-Fi адаптеры","rgw_page_wifi_adapters.html"],["Сетевые карты","rgw_page_network_cards.html"],["Точки доступа","rgw_page_access_points.html"],["Радиомосты","rgw_page_wireless_bridges.html"]]},
      {name:"Электропитание",icon:"🔋",items:[["UPS","rgw_page_ups.html"],["Батареи для UPS","rgw_page_ups_batteries.html"],["Стабилизаторы","rgw_page_stabilizers.html"],["Инверторы","rgw_page_inverters.html"],["Сетевые фильтры / пилоты","rgw_page_power_strips.html"]]},
      {name:"Видеонаблюдение",icon:"📹",items:[["IP-камеры","rgw_page_ip_cameras.html"],["Аналоговые камеры","rgw_page_analog_cameras.html"],["Домофоны","rgw_page_intercoms.html"],["Видеорегистраторы","rgw_page_video_recorders.html"]]},
      {name:"Серверное и сетевая инфраструктура",icon:"🗄️",items:[["Серверные шкафы","rgw_page_server_racks.html"],["Патч-панели","rgw_page_patch_panels.html"],["Коннекторы и розетки","rgw_page_connectors_outlets.html"],["Сетевые кабели","rgw_page_network_cables.html"],["IP-телефония","rgw_page_ip_telephony.html"],["Мини-АТС","rgw_page_mini_pbx.html"],["Сетевые аксессуары","rgw_page_network_accessories.html"]]},
      {name:"Аксессуары и хранение",icon:"💾",items:[["Внешние HDD/SSD","rgw_page_external_storage.html"],["Флешки","rgw_page_flash_drives.html"],["Карты памяти","rgw_page_memory_cards.html"],["Кабели","rgw_page_cables.html"],["Переходники","rgw_page_adapters.html"],["USB-хабы","rgw_page_usb_hubs.html"],["Сумки и рюкзаки","rgw_page_bags.html"],["DVD-приводы","rgw_page_dvd_drives.html"],["Проекторы и экраны","rgw_page_projectors_screens.html"],["Прочие аксессуары","rgw_page_other_accessories.html"]]}
    ];
    const trigger=document.getElementById('catalogTrigger'),menu=document.getElementById('catalogMenu'),closeButton=document.getElementById('catalogClose'),backdrop=document.getElementById('catalogBackdrop'),categoryBox=document.getElementById('megaCategories'),subBox=document.getElementById('megaSubcategories'),mobileBox=document.getElementById('mobileCatalog');
    function renderSubcategory(index){const category=catalogData[index];document.querySelectorAll('.mega-category').forEach((button,i)=>button.classList.toggle('active',i===index));subBox.innerHTML='<h3>'+category.icon+' '+category.name+'</h3><p>Выберите нужную подкатегорию</p><div class="mega-links">'+category.items.map(item=>'<a href="'+item[1]+'">'+item[0]+' <span>→</span></a>').join('')+'</div>';}
    categoryBox.innerHTML=catalogData.map((category,index)=>'<button class="mega-category'+(index===0?' active':'')+'" type="button" data-category-index="'+index+'"><span>'+category.icon+' '+category.name+'</span><span>›</span></button>').join('');
    categoryBox.querySelectorAll('.mega-category').forEach(button=>button.addEventListener('click',()=>renderSubcategory(Number(button.dataset.categoryIndex))));
    mobileBox.innerHTML=catalogData.map(category=>'<details><summary><span>'+category.icon+' '+category.name+'</span><span>⌄</span></summary><div class="mobile-links">'+category.items.map(item=>'<a href="'+item[1]+'">'+item[0]+' <span>→</span></a>').join('')+'</div></details>').join('');
    renderSubcategory(0);
    function setCatalog(open){menu.classList.toggle('open',open);backdrop.classList.toggle('open',open);trigger.setAttribute('aria-expanded',String(open));if(open)renderSubcategory(0);}
    trigger.addEventListener('click',()=>setCatalog(!menu.classList.contains('open')));closeButton.addEventListener('click',()=>setCatalog(false));backdrop.addEventListener('click',()=>setCatalog(false));
    document.addEventListener('click',event=>{if(menu.classList.contains('open')&&!event.target.closest('.header-shell'))setCatalog(false)});
    document.addEventListener('keydown',event=>{if(event.key==='Escape')setCatalog(false)});})();